@startuml
TimerForm : createTimer
TimerForm : updateTimer

App o-- TimerDashboard
TimerDashboard o-- TimerList
TimerDashboard o-- ToggleableTimerForm

TimerList  "1" *-- "*" EditableTimer

note "edit==true" as editTrue
note "edit==false" as editFalse

EditableTimer  o-- editTrue
 editTrue -- TimerForm

EditableTimer  "0-1  " o-- editFalse
editFalse -- "*" Timer

note "createTimer" as createTimer

ToggleableTimerForm o--createTimer
createTimer -- TimerForm







@enduml
